app/views.py
from flask import session
from app.utils.model_user_helper import UserHelper
from app.utils.model_schedule_helper import ScheduleHelper
from flask_login import (
    login_user,
    logout_user,
    login_required
)
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    jsonify,
    flash,
    url_for
)
import json


blueprint_default = Blueprint("views", __name__)

user_helper = UserHelper()
schedule_helper = ScheduleHelper()

@blueprint_default.route("/", methods=("GET", "POST"))
def index():
    from .forms import LoginForm
    form = LoginForm()

    context = {
        "form": form,
        "logged": False
    }

    if "_id" in session:
        context["logged"] = True
        return redirect(url_for("views.home"))

    return render_template("/account/index.html", context=context)


@blueprint_default.route("/cadastro", methods=("GET", "POST"))
def account_create():
    from .forms import UserForm
    user_form = UserForm()

    context = {
        "form": user_form,
        "logged": False
    }

    if "_id" in session:
        context["logged"] = True
        return redirect(url_for("views.home"))

    if request.method == "POST":
        if user_form.validate_on_submit():
            user_helper.new_user(
                full_name=request.form["full_name"],
                birthday=request.form["birthday"],
                email=request.form["email"],
                phone=request.form["phone"],
                password=request.form["password"],
            )

            user = user_helper.login(
                email=request.form["email"],
                password=request.form["password"]
            )

            if user:
                login_user(user)
                flash('Conta criada com sucesso!', 'success')
                return redirect(url_for("views.home"))

    return render_template("/account/account-create.html", context=context)


@blueprint_default.route("/login", methods=("POST",))
def login():
    from .forms import LoginForm
    user_form = LoginForm()

    if request.method == "POST":
        if user_form.validate_on_submit():
            user = user_helper.login(
                email=request.form["email"],
                password=request.form["password"]
            )

            if user:
                login_user(user)
                flash('Login efetuado com sucesso!', 'info')
                return redirect(url_for("views.home"))

    return redirect(url_for("views.index"))


@blueprint_default.route("/logout", methods=("GET",))
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.index"))


@blueprint_default.route("/inicio", methods=("GET", "POST"))
@login_required
def home():
    context = {
        "logged": True,
        "type_user": "",
        "user_id": session["_user_id"],
        "view_schedule": [],
        "not_confirmed": [],
        "scheduled": [],
        "history": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user
    context["view_schedule"] = user_helper.view_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )
    context["not_confirmed"] = user_helper.not_confirmed_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )
    context["scheduled"] = user_helper.scheduled_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )
    context["history"] = user_helper.history_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    return render_template("/home/index.html", context=context)


@blueprint_default.route("/agendar", methods=("GET", "POST"))
@login_required
def scheduling(date_calendar=None):
    form_schedule = ""
    type_user = user_helper.type_user(user_id=session["_user_id"])
    hour_schedule = schedule_helper.hour_of_schedule()

    if type_user == "establishment_user":
        from .forms import ScheduleFormeEstablishmentUser
        form_schedule = ScheduleFormeEstablishmentUser()
    else:
        from .forms import ScheduleFormCommonUser
        form_schedule = ScheduleFormCommonUser()

    context = {
        "form": form_schedule,
        "logged": True,
        "hour_schedule": hour_schedule
    }

    if request.method == "POST":
        if form_schedule.validate_on_submit():
            if type_user == "establishment_user":
                schedule = user_helper.user_scheduling(
                    date=request.form["date"],
                    time=request.form["time"],
                    common_user_id=request.form["user"],
                    establishment_user_id=session["_user_id"],
                    note=request.form["note"],
                )
            else:
                schedule = user_helper.user_scheduling(
                    date=request.form["date"],
                    time=request.form["time"],
                    common_user_id=session["_user_id"],
                    note=request.form["note"],
                )

            if schedule:
                flash(
                    'Agendamento enviado com sucesso! Pendente de confirmação.',
                    'info'
                )
            else:
                if type_user == "establishment_user":
                    flash(
                        (
                            'Não foi possível agendar. '
                            'Cliente já possui um agendamento '
                            'pendente ou date e hora indisponível.'
                        ),
                        'warning'
                    )
                else:
                    flash(
                        (
                            'Não foi possível agendar. '
                            'Agendamento pendente ou '
                            'data e hora indisponível'
                        ),
                        'warning'
                    )
            return redirect(url_for("views.home"))

    return render_template(
        "/schedule/index.html",
        context=context,
        date_calendar=date_calendar
    )


@blueprint_default.route("/confirmar", methods=("GET","POST"))
@login_required
def schedule_check():
    context = {
        "logged": True,
        "type_user" : "",
        "not_confirmed": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    if request.method == "POST":
        user_helper.scheduling_confirmation(user_id=request.form["user_id"])

    context["not_confirmed"] = user_helper.not_confirmed_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["not_confirmed"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-check.html", context=context)


@blueprint_default.route("/cancelar", methods=("GET", "POST"))
@login_required
def schedule_cancel():
    context = {
        "logged": True,
        "type_user" : "",
        "scheduled": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    if request.method == "POST":
        user_helper.scheduling_cancelation(user_id=request.form["user_id"])

    context["scheduled"] = user_helper.scheduled_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["scheduled"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-cancel.html", context=context)


@blueprint_default.route("/visualizar", methods=("GET", "POST"))
@login_required
def schedule_view():
    context = {
        "logged": True,
        "type_user" : "",
        "view_schedule": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    context["view_schedule"] = user_helper.view_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["view_schedule"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-view.html", context=context)


@blueprint_default.route("/historico", methods=("GET","POST"))
@login_required
def history():
    context = {
        "logged": True,
        "type_user" : "",
        "history": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    context["history"] = user_helper.history_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["history"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-history.html", context=context)

@blueprint_default.route("/calendario", methods=("GET", "POST"))
@login_required
def calendar():
    context = {
        "logged" : True,
    }

    calendar_level = schedule_helper.schedules_day_level()

    levels = []

    for key, item in calendar_level.items():
        levels.append((key, item))

    return render_template(
        "/calendar/index.html",
        context=context,
        levels=json.dumps(levels)
    )


@blueprint_default.route("/calendario/detalhes", methods=("POST",))
@login_required
def calendar_detail():
    context = {
        "logged": True,
        "schedules": {},
        "date_picked" : ""
    }
    if request.method == "POST":
        if "date-picked" in request.form:
            date_picked = request.form["date-picked"]
            context["date_picked"] = date_picked

            if date_picked:
                calendar_info = schedule_helper.calendar_schedules(
                    date=date_picked
                )
            else:
                calendar_info = schedule_helper.calendar_schedules()

            context["schedules"] = calendar_info
    return render_template("/calendar/detail.html", context=context)

app/templates/components/buttons-home-common.html
<div class="d-flex flex-row flex-wrap justify-content-center">
  <a href="{{ url_for('views.scheduling') }}" class="btn btn-square bg-primary m-2">
    <img src="{{ url_for('static', filename='images/icons/clock.svg') }}" class="icon"></i>
    <span>Agendar</span>
  </a>
  <a href="{{ url_for('views.calendar') }}" class="btn btn-square bg-primary m-2">
    <img src="{{ url_for('static', filename='images/icons/calendar.svg') }}" class="icon"></i>
    <span>Calendário</span>
  </a>
  {% if context["view_schedule"]|length > 0 %}
  <button type="button" class="btn btn-square bg-primary m-2" data-bs-toggle="modal" data-bs-target="#view-modal">
    <img src="{{ url_for('static', filename='images/icons/eye.svg') }}" class="icon"></i>
    <span>Visualizar</span>
  </button>
  {% endif %}
  {% if context["not_confirmed"]|length > 0 %}
  <button type="button" class="btn btn-square bg-primary m-2" data-bs-toggle="modal" data-bs-target="#check-modal">
    <img src="{{ url_for('static', filename='images/icons/calendar-check.svg') }}" class="icon"></i>
    <span>Confirmar</span>
  </button>
  {% endif %}
  {% if context["scheduled"]|length > 0 %}
  <button type="button" class="btn btn-square bg-primary m-2" data-bs-toggle="modal" data-bs-target="#cancel-modal">
    <img src="{{ url_for('static', filename='images/icons/x-circle.svg') }}" class="icon"></i>
    <span>Cancelar</span>
  </button>
  {% endif %}
</div>

app/templates/components/calendar.html
<div id="calendar" class="col-12 col-md-6 mb-5"></div>

<div class="col-12 d-flex flex-nowrap justify-content-center">
  <div class="col-12 col-md-5 d-flex flex-nowrap justify-content-around">
    <div class="mb-3">
      <a href="{{ url_for('views.home') }}" class="btn btn-warning btn-lg px-2 px-md-auto m-0">
        <span class="text-light">Inicio</span>
        <img src="{{ url_for('static', filename='images/icons/home.svg') }}" class="icon-row"></i>
      </a>
    </div>
    <div class="mb-3">
      <form id="form-calendar" name="form-calendar" method="POST" action="{{ url_for('views.calendar_detail') }}">
        <input type="hidden" id="date-picked" name="date-picked" value="">
        <button type="submit"  class="btn btn-success btn-lg px-auto m-0">
          <span class="text-light">Ver Agenda</span>
          <img src="{{ url_for('static', filename='images/icons/calendar.svg') }}" class="icon-row"></i>
        </button>
      </form>
    </div>
  </div>
</div>

<input type="hidden" id="levels" name="levels" value="{{levels}}">

{% block extra_scripts_bottom %}
<script src="{{ url_for('static', filename='js/submit_date.js') }}"></script>
<script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
{% endblock %}

app/templates/components/footer.html
<footer class="d-flex flex-row py-5">
  <div class="col-md-12">
    <div class="row justify-content-center">
      <div class="col-9 col-md-8 col-lg-6">
        <p class="text-center text-muted">
          Este sistema foi criado para o trabalho de conclusão da
          <strong>Faculde Alcides Maya Tecnologia</strong>.
          <br>Autor <strong>Lucas da Silva Pereira</strong>.
          <br><small>Contato: lucas.pereira.244@gmail.com</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/templates/components/form-create-account.html
<div class="row justify-content-center py-md-4">
  <div class="col-9 col-md-8 col-lg-6 py-md-4">
    <form name="form-account-create" id="form-account-create" class="form" method="POST" action="{{ url_for('views.account_create') }}">
      {{ context['form'].csrf_token }}
      {% for form in context['form'] %}
        {% if 'csrf_token' != form.name %}
          <div class="form-group input-group-lg pt-2 pt-md-3">
            {{ form.label }}
            {{ form }}
          </div>
          {% if form.errors %}
            <div class="alert alert-danger mt-2" role="alert">
              <ul class="errors">
                {% for error in form.errors %}
                <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          {% endif %}
        {% endif %}
      {% endfor %}
      <div class="d-grid gap-2 pt-3">
        <button type="submit" class="btn btn-primary btn-lg my-2 mx-3">
          Cadastrar
          <img src="{{ url_for('static', filename='images/icons/floppy-disk.svg') }}" class="icon-account">
        </button>
      </div>
      <div class="col-12 text-center pt-3">
        <a href="{{ url_for('views.index') }}">Voltar</a>
      </div>
    </form>
  </div>
</div>

app/templates/components/form-login.html
<div class="row justify-content-center py-md-4">
  <div class="col-9 col-md-8 col-lg-6 py-md-4">
    <form class="form" action="{{ url_for('views.login') }}" method="POST">
      {{ context['form'].csrf_token }}
      {% for form in context['form'] %}
        {% if 'csrf_token' != form.name %}
        <div class="form-group input-group-lg">
          {{ form.label }}
          {{ form }}
        </div>
        {% endif %}
      {% endfor %}
      <div class="d-grid gap-2 pt-3">
        <button type="submit" class="btn btn-primary btn-lg my-2 mx-3">
          Entrar
          <img src="{{ url_for('static', filename='images/icons/login.svg') }}" class="icon-account">
        </button>
      </div>
      <div class="col-12 text-center pt-3">
        <a href="{{ url_for('views.account_create') }}">Cadastre-se</a>
      </div>
    </form>
  </div>
</div>

app/templates/components/form-scheduling.html
<div class="row justify-content-center py-md-4">
  <div class="col-12 col-sm-6 col-lg-5 col-xl-4 col-xxl-3 py-md-4">
    <form class="form" id="form-scheduling" name="form-scheduling" action="{{ url_for('views.scheduling') }}" method="POST">
      <div class="row form-group input-group-lg">
        {{ context['form'].csrf_token }}
        {% for form in context['form'] %}
          {% if 'csrf_token' != form.name %}
          <div class="form-group input-group-lg">
            {{ form.label }}
            {{ form }}
          </div>
          {% endif %}
        {% endfor %}
      </div>

      <div class="d-flex justify-content-around pt-3">
        Atendimento das {{context['hour_schedule']['ini']}}H até {{context['hour_schedule']['end']}}H
      </div>
      <div class="d-flex justify-content-around pt-3">
        <a href="{{ url_for('views.home') }}" class="btn btn-warning btn-lg px-2 px-md-auto m-0">
          <span class="text-light">Inicio</span>
          <img src="{{ url_for('static', filename='images/icons/home.svg') }}" class="icon-row"></i>
        </a>
        <button type="submit" class="btn btn-primary btn-lg px-2 px-md-auto m-0">
          <span>Agendar</span>
          <img src="{{ url_for('static', filename='images/icons/clock-check.svg') }}" class="icon-row">
        </button>
      </div>
    </form>
  </div>
</div>

app/templates/components/head-banner.html
<header class="col-12 p-3 p-md-5 banner-head"></header>

app/templates/components/list-cancel-establishment.html
{% if context["scheduled"]|length > 0 %}
<div class="col-12 col-md-10 col-lg-8 d-flex flex-wrap justify-content-center">
  <span class="p-2">
    Clientes Agendados
  </span>
  {% for schedules in context["scheduled"] %}
  <div class="col-12 d-flex flex-nowrap rounded bg-light text-center p-2 mb-1">
    <div class="col-3 p-1">
      <span>{{ schedules["full_name"] }}</span>
    </div>
    <div class="col-3 p-1">
      <span>{{ schedules["date"] }}</span>
    </div>
    <div class="col-3 p-1">
      <span>{{ schedules["hour"] }}</span>
    </div>
    <div class="col-3 p-1">
      <form action="{{ url_for('views.schedule_cancel') }}" name="form-cancel{{ schedules['user_id'] }}" class="p-0 m-0" method="POST">
        <input type="hidden" name="user_id" value="{{ schedules['user_id'] }}">
        <button type="submit"  class="btn btn-danger btn-sm" onclick="return pergunta();">
          <img src="{{ url_for('static', filename='images/icons/x-circle.svg') }}" class="icon-row p-0 m-0">
        </button>
      </form>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="col-12  d-flex flex-nowrap justify-content-center mt-5">
  <div class="col-12 col-md-8 col-lg-5 mb-3 text-center">
    <p>Não existem agendamentos pendentes.</p>
    <img src="{{ url_for('static', filename='images/icons/schedule_not_found.svg') }}" width="100%">
  </div>
</div>
{% endif %}
{% block extra_scripts_bottom %}
<script src="{{ url_for('static', filename='js/submit_confirm_cancel.js') }}"></script>
{% endblock %}

app/templates/components/list-check-establishment.html
{% if context["not_confirmed"]|length > 0 %}
<div class="col-12 col-md-10 col-lg-8 d-flex flex-wrap justify-content-center">
  <span class="p-2">
    Clientes Agendados
  </span>
  {% for schedules in context["not_confirmed"] %}
  <div class="col-12 d-flex flex-nowrap rounded bg-light text-center p-2 mb-1">
    <div class="col-3 p-1">
      <span>{{ schedules["full_name"] }}</span>
    </div>
    <div class="col-3 p-1">
      <span>{{ schedules["date"] }}</span>
    </div>
    <div class="col-3 p-1">
      <span>{{ schedules["hour"] }}</span>
    </div>
    <div class="col-3 p-1">
      <form action="{{ url_for('views.schedule_check') }}" class="p-0 m-0" method="POST">
        <input type="hidden" name="user_id" value="{{ schedules['user_id'] }}">
        <button type="submit"  class="btn btn-success btn-sm" onclick="return pergunta();">
          <img src="{{ url_for('static', filename='images/icons/check-circle.svg') }}" class="icon-row p-0 m-0">
        </button>
      </form>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="col-12  d-flex flex-nowrap justify-content-center mt-5">
  <div class="col-12 col-md-8 col-lg-5 mb-3 text-center">
    <p>Não existem agendamentos pendentes.</p>
    <img src="{{ url_for('static', filename='images/icons/schedule_not_found.svg') }}" width="100%">
  </div>
</div>
{% endif %}
{% block extra_scripts_bottom %}
<script src="{{ url_for('static', filename='js/submit_confirm_scheduling.js') }}"></script>
{% endblock %}

app/templates/components/list-history-establishment.html
{% if context["history"]|length > 0 %}
<div class="col-12 col-md-10 col-lg-8 d-flex flex-wrap justify-content-center">
  <span class="p-2">
    Clientes Agendados
  </span>
  {% for schedules in context["history"] %}
  <div class="col-12 d-flex flex-nowrap rounded bg-light text-center p-2 mb-1">
    <div class="col-4 p-1">
      <span>{{ schedules["full_name"] }}</span>
    </div>
    <div class="col-4 p-1">
      <span>{{ schedules["date"] }}</span> 
      <span>{{ schedules["hour"] }}</span>
    </div>
    <div class="col-4 p-1">
      <span>{{ schedules["status"] }}</span>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="col-12  d-flex flex-nowrap justify-content-center mt-5">
  <div class="col-12 col-md-8 col-lg-5 mb-3 text-center">
    <p>Não existem agendamentos pendentes.</p>
    <img src="{{ url_for('static', filename='images/icons/schedule_not_found.svg') }}" width="100%">
  </div>
</div>
{% endif %}

app/templates/components/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand ms-3" href="{{ url_for('views.index') }}">
      <img src="{{ url_for('static', filename='images/logo-nav.svg') }}" alt="logotipo hora na agenda">
    </a>
    {% if context["logged"] %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{{ url_for('views.home') }}" class="nav-link active" aria-current="page">Inicio</a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('views.scheduling') }}" class="nav-link">Agendamento</a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('views.calendar') }}" class="nav-link">Calendario</a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('views.home') }}" class="nav-link disabled" tabindex="-1" aria-disabled="true">Perfil</a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('views.logout') }}" class="nav-link" href="#" tabindex="-1" aria-disabled="true">Sair</a>
        </li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>

app/templates/components/recaptcha.html
<div class="g-recaptcha" data-sitekey=""></div>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>

app/templates/components/schedule-cancel.html
<div class="modal" id="cancel-modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cancelar</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex flex-wrap">
          {% for schedule in context["scheduled"] %}
          <span class="px-0 pb-1">
            Status do Agendamento
          </span>
          <div class="col-12 rounded bg-info text-center p-2 mb-2">
            <span class="px-0">{{ schedule["status"] }}</span>
          </div>
          <span class="px-0 pb-1">
            Data do ultimo Agendamento
          </span>
          <div class="col-12 rounded bg-info text-center p-2 mb-2">
            <span class="px-0">{{ schedule["date"] }}</span>
          </div>
          <span class="px-0 pb-1">
            Hora do ultimo Agendamento
          </span>
          <div class="col-12 rounded bg-info text-center p-2 mb-2">
            <span class="px-0">{{ schedule["hour"] }}</span>
          </div>
          <span class="px-0 pb-1">
            Observações
          </span>
          <div class="col-12 rounded bg-info text-center p-2">
            <span class="px-0">{{ schedule["note"] }}</span>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="modal-footer">
        <div class="col-12 d-flex flex-nowrap justify-content-around">
          <div class="mb-3">
            <button type="button" class="btn btn-warning btn-lg px-auto m-0" data-bs-dismiss="modal">
              <span class="text-light">Voltar</span>
              <img src="{{ url_for('static', filename='images/icons/back-arrow.svg') }}" class="icon-row"></i>
            </button>
          </div>
          <form action="{{url_for('views.schedule_cancel')}}" id="form-cancel{{context['user_id']}}" name="form-cancel{{context['user_id']}}" method="POST">
            <input type="hidden" name="user_id" value="{{ context['user_id'] }}">
            <button type="submit"  class="btn btn-danger btn-lg px-auto m-0" onclick="return pergunta();">
              <span class="text-light">Cancelar</span>
              <img src="{{ url_for('static', filename='images/icons/x-circle.svg') }}" class="icon-row"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% block extra_scripts_bottom %}
<script src="{{ url_for('static', filename='js/submit_confirm_cancel.js') }}"></script>
{% endblock %}

app/templates/components/schedule-check.html
<div class="modal" id="check-modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirmar</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex flex-wrap">
          {% for schedule in context["not_confirmed"] %}
          <span class="px-0 pb-1">
            Status do Agendamento
          </span>
          <div class="col-12 rounded bg-info text-center p-2 mb-2">
            <span class="px-0">{{ schedule["status"] }}</span>
          </div>
          <span class="px-0 pb-1">
            Data do ultimo Agendamento
          </span>
          <div class="col-12 rounded bg-info text-center p-2 mb-2">
            <span class="px-0">{{ schedule["date"] }}</span>
          </div>
          <span class="px-0 pb-1">
            Hora do ultimo Agendamento
          </span>
          <div class="col-12 rounded bg-info text-center p-2 mb-2">
            <span class="px-0">{{ schedule["hour"] }}</span>
          </div>
          <span class="px-0 pb-1">
            Observações
          </span>
          <div class="col-12 rounded bg-info text-center p-2">
            <span class="px-0">{{ schedule["note"] }}</span>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="modal-footer">
        <div class="col-12 d-flex flex-nowrap justify-content-around">
          <div class="mb-3">
            <button type="button" class="btn btn-warning btn-lg px-auto m-0" data-bs-dismiss="modal">
              <span class="text-light">Voltar</span>
              <img src="{{ url_for('static', filename='images/icons/back-arrow.svg') }}" class="icon-row"></i>
            </button>
          </div>
          <form action="{{ url_for('views.schedule_check') }}" method="POST">
            <input type="hidden" name="user_id" value="{{ context['user_id'] }}">
            <button type="submit"  class="btn btn-success btn-lg px-auto m-0" onclick="return pergunta();">
              <span class="text-light">Confirmar</span>
              <img src="{{ url_for('static', filename='images/icons/clock-check.svg') }}" class="icon-row"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% block extra_scripts_bottom %}
<script src="{{ url_for('static', filename='js/submit_confirm_scheduling.js') }}"></script>
{% endblock %}