app/views.py
from flask import session
from app.utils.model_user_helper import UserHelper
from app.utils.model_schedule_helper import ScheduleHelper
from flask_login import (
    login_user,
    logout_user,
    login_required
)
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    jsonify,
    flash,
    url_for
)
import json


blueprint_default = Blueprint("views", __name__)

user_helper = UserHelper()
schedule_helper = ScheduleHelper()

@blueprint_default.route("/", methods=("GET", "POST"))
def index():
    from .forms import LoginForm
    form = LoginForm()

    context = {
        "form": form,
        "logged": False
    }

    if "_id" in session:
        context["logged"] = True
        return redirect(url_for("views.home"))

    return render_template("/account/index.html", context=context)


@blueprint_default.route("/cadastro", methods=("GET", "POST"))
def account_create():
    from .forms import UserForm
    user_form = UserForm()

    context = {
        "form": user_form,
        "logged": False
    }

    if "_id" in session:
        context["logged"] = True
        return redirect(url_for("views.home"))

    if request.method == "POST":
        if user_form.validate_on_submit():
            user_helper.new_user(
                full_name=request.form["full_name"],
                birthday=request.form["birthday"],
                email=request.form["email"],
                phone=request.form["phone"],
                password=request.form["password"],
            )

            user = user_helper.login(
                email=request.form["email"],
                password=request.form["password"]
            )

            if user:
                login_user(user)
                flash('Conta criada com sucesso!', 'success')
                return redirect(url_for("views.home"))

    return render_template("/account/account-create.html", context=context)


@blueprint_default.route("/login", methods=("POST",))
def login():
    from .forms import LoginForm
    user_form = LoginForm()

    if request.method == "POST":
        if user_form.validate_on_submit():
            user = user_helper.login(
                email=request.form["email"],
                password=request.form["password"]
            )

            if user:
                login_user(user)
                flash('Login efetuado com sucesso!', 'info')
                return redirect(url_for("views.home"))

    return redirect(url_for("views.index"))


@blueprint_default.route("/logout", methods=("GET",))
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.index"))


@blueprint_default.route("/inicio", methods=("GET", "POST"))
@login_required
def home():
    context = {
        "logged": True,
        "type_user": "",
        "user_id": session["_user_id"],
        "view_schedule": [],
        "not_confirmed": [],
        "scheduled": [],
        "history": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user
    context["view_schedule"] = user_helper.view_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )
    context["not_confirmed"] = user_helper.not_confirmed_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )
    context["scheduled"] = user_helper.scheduled_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )
    context["history"] = user_helper.history_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    return render_template("/home/index.html", context=context)


@blueprint_default.route("/agendar", methods=("GET", "POST"))
@login_required
def scheduling(date_calendar=None):
    form_schedule = ""
    type_user = user_helper.type_user(user_id=session["_user_id"])
    hour_schedule = schedule_helper.hour_of_schedule()

    if type_user == "establishment_user":
        from .forms import ScheduleFormeEstablishmentUser
        form_schedule = ScheduleFormeEstablishmentUser()
    else:
        from .forms import ScheduleFormCommonUser
        form_schedule = ScheduleFormCommonUser()

    context = {
        "form": form_schedule,
        "logged": True,
        "hour_schedule": hour_schedule
    }

    if request.method == "POST":
        if form_schedule.validate_on_submit():
            if type_user == "establishment_user":
                schedule = user_helper.user_scheduling(
                    date=request.form["date"],
                    time=request.form["time"],
                    common_user_id=request.form["user"],
                    establishment_user_id=session["_user_id"],
                    note=request.form["note"],
                )
            else:
                schedule = user_helper.user_scheduling(
                    date=request.form["date"],
                    time=request.form["time"],
                    common_user_id=session["_user_id"],
                    note=request.form["note"],
                )

            if schedule:
                flash(
                    'Agendamento enviado com sucesso! Pendente de confirmação.',
                    'info'
                )
            else:
                if type_user == "establishment_user":
                    flash(
                        (
                            'Não foi possível agendar. '
                            'Cliente já possui um agendamento '
                            'pendente ou date e hora indisponível.'
                        ),
                        'warning'
                    )
                else:
                    flash(
                        (
                            'Não foi possível agendar. '
                            'Agendamento pendente ou '
                            'data e hora indisponível'
                        ),
                        'warning'
                    )
            return redirect(url_for("views.home"))

    return render_template(
        "/schedule/index.html",
        context=context,
        date_calendar=date_calendar
    )


@blueprint_default.route("/confirmar", methods=("GET","POST"))
@login_required
def schedule_check():
    context = {
        "logged": True,
        "type_user" : "",
        "not_confirmed": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    if request.method == "POST":
        user_helper.scheduling_confirmation(user_id=request.form["user_id"])

    context["not_confirmed"] = user_helper.not_confirmed_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["not_confirmed"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-check.html", context=context)


@blueprint_default.route("/cancelar", methods=("GET", "POST"))
@login_required
def schedule_cancel():
    context = {
        "logged": True,
        "type_user" : "",
        "scheduled": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    if request.method == "POST":
        user_helper.scheduling_cancelation(user_id=request.form["user_id"])

    context["scheduled"] = user_helper.scheduled_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["scheduled"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-cancel.html", context=context)


@blueprint_default.route("/visualizar", methods=("GET", "POST"))
@login_required
def schedule_view():
    context = {
        "logged": True,
        "type_user" : "",
        "view_schedule": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    context["view_schedule"] = user_helper.view_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["view_schedule"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-view.html", context=context)


@blueprint_default.route("/historico", methods=("GET","POST"))
@login_required
def history():
    context = {
        "logged": True,
        "type_user" : "",
        "history": [],
    }
    type_user = user_helper.type_user(
        user_id=session["_user_id"]
    )
    context["type_user"] = type_user

    context["history"] = user_helper.history_schedule(
        user_id = session["_user_id"],
        type_user = type_user
    )

    if not context["history"]:
        return redirect(url_for("views.home"))

    return render_template("/home/schedule-history.html", context=context)

@blueprint_default.route("/calendario", methods=("GET", "POST"))
@login_required
def calendar():
    context = {
        "logged" : True,
    }

    calendar_level = schedule_helper.schedules_day_level()

    levels = []

    for key, item in calendar_level.items():
        levels.append((key, item))

    return render_template(
        "/calendar/index.html",
        context=context,
        levels=json.dumps(levels)
    )


@blueprint_default.route("/calendario/detalhes", methods=("POST",))
@login_required
def calendar_detail():
    context = {
        "logged": True,
        "schedules": {},
        "date_picked" : ""
    }
    if request.method == "POST":
        if "date-picked" in request.form:
            date_picked = request.form["date-picked"]
            context["date_picked"] = date_picked

            if date_picked:
                calendar_info = schedule_helper.calendar_schedules(
                    date=date_picked
                )
            else:
                calendar_info = schedule_helper.calendar_schedules()

            context["schedules"] = calendar_info
    return render_template("/calendar/detail.html", context=context)

app/templates/account-create.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="login-body h-md-100">
  <div class="col-12 col-md-6 py-5 background-left h-md-100">
    <div class="row justify-content-center pt-md-5">
      <div class="col-9 col-md-8 col-lg-6 py-5 px-4 bg-text text-light fs-5">
        Hora na Agenda é um sistema de agendamento para salões e barbearias, criado para ser fácil e simples.
      </div>
    </div>
  </div>
  <div class="col-12 col-md-6 px-3 py-5 h-md-100">
    {% include "components/form-create-account.html" %}
  </div>
</div>
{% endblock %}

{% block extra_scripts %}

{% endblock %}

app/templates/base-login.html
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=9">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Agenda {% block title %}{% endblock %}</title>
</head>

<body class="py-4">
    <div class="container">
        {% block content %}{% endblock %}

        {% include "components/footer.html" %}

        {% block scripts %}{% endblock %}
    </div>
</body>
</html>

app/templates/base.html
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/fav-schedule-time.svg') }}" type="image/x-icon">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/media.css') }}">
  {% block extra_css %}{% endblock %}
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
  {% block extra_scripts_top %}{% endblock %}
  <title>Hora na Agenda {% block title %}{% endblock %}</title>
</head>

<body>
  {% include "components/navbar.html" %}
  <div class="row h-100">
    {% block content %}{% endblock %}

    {% include "components/footer.html" %}

  </div>
  {% block extra_scripts_bottom %}{% endblock %}
</body>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
{% include "components/head-banner.html" %}
<div class="row d-flex flex-row justify-content-center">
  <div class="col-md-10 p-5">
    <div class="d-flex flex-row flex-wrap justify-content-center">
      <a href="{{ url_for('views.scheduling') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/clock.svg') }}" class="icon"></i>
        <span>Agendar</span>
      </a>

      <a href="{{ url_for('views.schedule') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/arrival-time.svg') }}" class="icon"></i>
        <span>Horário</span>
      </a>

      <a href="{{ url_for('views.calendar') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/calendar.svg') }}" class="icon"></i>
        <span>Calendário</span>
      </a>

      <a href="{{ url_for('views.history') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/history.svg') }}" class="icon"></i>
        <span>Histórico</span>
      </a>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_scripts %}

{% endblock %}

app/templates/reschedule.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
{% include "components/head-banner.html" %}
<div class="row d-flex flex-row justify-content-center">
  <div class="col-md-10 p-5">
    <div class="d-flex flex-row flex-wrap justify-content-center">
      {% include "components/form-reschedule.html" %}
    </div>
  </div>
</div>
{% endblock %}

{% block extra_scripts %}

{% endblock %}

app/templates/schedule.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
{% include "components/head-banner.html" %}
<div class="row d-flex flex-row justify-content-center">
  <div class="col-md-10 p-5">
    <div class="d-flex flex-row flex-wrap justify-content-center">
      <a href="{{ url_for('views.view_schedule') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/eye.svg') }}" class="icon"></i>
        <span>Visualizar</span>
      </a>

      <a href="{{ url_for('views.cancel_schedule') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/x-circle.svg') }}" class="icon"></i>
        <span>Cancelar</span>
      </a>

      <a href="{{ url_for('views.check_schedule') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/calendar-check.svg') }}" class="icon"></i>
        <span>Confirmar</span>
      </a>

      <a href="{{ url_for('views.history') }}" class="btn btn-square bg-primary m-2">
        <img src="{{ url_for('static', filename='images/icons/history.svg') }}" class="icon"></i>
        <span>Histórico</span>
      </a>
    </div>
  </div>
</div>
<div class="d-flex col-12 bg-light justify-content-center mt-5">
  <a href="javascript:javascript:history.go(-1)" class="btn btn-warning btn-lg">
    <span class="text-dark">Voltar</span>
    <img src="{{ url_for('static', filename='images/icons/back-arrow.svg') }}" class="icon-row"></i>
  </a>
</div>
{% endblock %}

{% block extra_scripts %}

{% endblock %}

app/templates/scheduling.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
{% include "components/head-banner.html" %}
<div class="row d-flex flex-row justify-content-center">
  <div class="col-md-10 p-5">
    <div class="d-flex flex-row flex-wrap justify-content-center">
      {% include "components/form-scheduling.html" %}
    </div>
  </div>
</div>
{% endblock %}

{% block extra_scripts %}

{% endblock %}